package interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public class EIntC extends BasicExpr {
  public final String qinteger_;

  public EIntC(String p1) { qinteger_ = p1; }

  public <R,A> R accept(interpreter.query.Absyn.BasicExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof interpreter.query.Absyn.EIntC) {
      interpreter.query.Absyn.EIntC x = (interpreter.query.Absyn.EIntC)o;
      return this.qinteger_.equals(x.qinteger_);
    }
    return false;
  }

  public int hashCode() {
    return this.qinteger_.hashCode();
  }


}
