# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\"\x15\n\x08PathName\x12\t\n\x01p\x18\x01 \x01(\t\"G\n\x03ZMI\x12\x16\n\x01s\x18\x01 \x03(\x0b\x32\x0b.ZMI.SEntry\x1a(\n\x06SEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32(\n\x05\x41gent\x12\x1f\n\x07GetZone\x12\t.PathName\x1a\t.PathNameB\x06\n\x04\x63oreb\x06proto3')
)




_PATHNAME = _descriptor.Descriptor(
  name='PathName',
  full_name='PathName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='PathName.p', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=36,
)


_ZMI_SENTRY = _descriptor.Descriptor(
  name='SEntry',
  full_name='ZMI.SEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ZMI.SEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ZMI.SEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=109,
)

_ZMI = _descriptor.Descriptor(
  name='ZMI',
  full_name='ZMI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='ZMI.s', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ZMI_SENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=109,
)

_ZMI_SENTRY.containing_type = _ZMI
_ZMI.fields_by_name['s'].message_type = _ZMI_SENTRY
DESCRIPTOR.message_types_by_name['PathName'] = _PATHNAME
DESCRIPTOR.message_types_by_name['ZMI'] = _ZMI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathName = _reflection.GeneratedProtocolMessageType('PathName', (_message.Message,), dict(
  DESCRIPTOR = _PATHNAME,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:PathName)
  ))
_sym_db.RegisterMessage(PathName)

ZMI = _reflection.GeneratedProtocolMessageType('ZMI', (_message.Message,), dict(

  SEntry = _reflection.GeneratedProtocolMessageType('SEntry', (_message.Message,), dict(
    DESCRIPTOR = _ZMI_SENTRY,
    __module__ = 'agent_pb2'
    # @@protoc_insertion_point(class_scope:ZMI.SEntry)
    ))
  ,
  DESCRIPTOR = _ZMI,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:ZMI)
  ))
_sym_db.RegisterMessage(ZMI)
_sym_db.RegisterMessage(ZMI.SEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\004core'))
_ZMI_SENTRY.has_options = True
_ZMI_SENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='Agent',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=111,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetZone',
    full_name='Agent.GetZone',
    index=0,
    containing_service=None,
    input_type=_PATHNAME,
    output_type=_PATHNAME,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
