# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agent_pb2 as agent__pb2


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetZone = channel.unary_unary(
        '/Agent/GetZone',
        request_serializer=agent__pb2.PathName.SerializeToString,
        response_deserializer=agent__pb2.PathName.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetZone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetZone': grpc.unary_unary_rpc_method_handler(
          servicer.GetZone,
          request_deserializer=agent__pb2.PathName.FromString,
          response_serializer=agent__pb2.PathName.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
